# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=4, unique=True)),
                ('name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('perdiem_rate', models.IntegerField(null=True)),
            ],
        ),
    ]
